# Generated by Django 3.2.13 on 2022-05-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mindmap',
            name='leafs',
        ),
        migrations.AddField(
            model_name='leaf',
            name='mindmap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leafs', to='core.mindmap'),
        ),
    ]
