# Generated by Django 3.2.13 on 2022-05-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mindmap',
            old_name='leaves',
            new_name='leafs',
        ),
    ]
